### ISSUE TITLE
constructing struct/vector/array literals from expressions

### ISSUE THREAD

**Issue by j-hui** [shux-lang/shux#10]
we should support this – if we want to encourage immutable data, we _need_ to support the initialisation of literals via the dynamic values of expressions, rather than have the programmer declare a mutable data type and manually assign those fields.

**Comment by j-hui** [comment]
@Contentmaudlin i think we need to go back and tweak the parser in order to get this to work – this'll go back to the problem with vector literals....

**Comment by j-hui** [comment]
@cerrno would we consider any other kind of syntax for defining vector literals? Like instead of using `<x, y>`, doing something like `[x, y]` or `[[x, y]]` or `(x, y)` or wtv. just something that makes it go down our parser easier 

although I don't think something like `<<x, y>>` should be used, because that just completely fucks with any future potential for supporting `<<` and `>>` bitshift operators

**Comment by lucas-schuermann** [comment]
I think any of your proposed options would be fine. Not attached to <x,y> at all

**Comment by j-hui** [comment]
will PR a patch for that after I finish the parser -> ast work

**Comment by j-hui** [comment]
atm what we have is `[[` and `]]` – by introducing a new symbol, we reduce the possibility for it not really knowing whether or not our vectors are nested expressions, function calls, less than/greater than signs, etc.

The problem now is that we can't do something like `[[3, 4, 5], [5, 3, 21]]` – that would just give us a syntax error, because it would parse `[[` and `]]` as single tokens. worse, shit like `[[[4, 5], [4,4]], [[4], [5,5]]]` would lead to some weird ass results.

**Comment by j-hui** [comment]
Fixed in #15 

we're using `(x, y)` syntax, but we're only allowing vectors of dimensionality greater than 2.

we're still sticking with `vector<2>` for type notation though.
