### ISSUE TITLE
nested structs aren't allowed

### ISSUE THREAD

**Issue by lucas-schuermann** [shux-lang/shux#101]
```
struct foo {
   int x;
   struct bar {
      scalar y;
      string n;
   }
}

kn main() int {
   0
}
```

doesn't compile... it should if we are allowing nested structs, correct?

**Comment by Contentmaudlin** [comment]
Nah. Allowing this would require us to change the parser right now, which I'm against. Let's just stick with the following convention instead: 

```
struct bar { 
    scalar y;
    scalar n;
}

struct foo { 
    int x;
    struct bar b;
}

...
```

This will compile fine.

**Comment by lucas-schuermann** [comment]
Sounds good. Updating tests accordingly.
