### ISSUE TITLE
vector can be initialized with non-scalar

### ISSUE THREAD

**Issue by lucas-schuermann** [shux-lang/shux#104]
```
kn main() int {
   vector<2> g = (1, 2);
   0
}
```

compiles without incident. unless this is throwing a warning due to a conversation from int to scalar, this should be disallowed, correct? or do we do type conversion with atoms nicely?

**Comment by Contentmaudlin** [comment]
What is more impressive in our language is the great `shux` construct of string vectors:

```
kn main() int {
   vector<2> g = ("a", "b"); /* this compiles lol */ 
   0
}
```

**Comment by Contentmaudlin** [comment]
I'll fix this lol.
