### ISSUE TITLE
indexing into vectors isn't allowed

### ISSUE THREAD

**Issue by lucas-schuermann** [shux-lang/shux#105]
```
kn main() int {
   vector<2> g;
   g[0] = 2.0;
   0
}
```

this should be allowed--indexing needs to be fixed so that vectors are not treated as immutable types

**Comment by Contentmaudlin** [comment]
So are we saying that `vector`s are mutable by default? @j-hui @cerrno 

This works if `g` is declared with `var` above.

Note that once vectors are nested inside structs, a `var` keyword would be necessary anyway.

**Comment by lucas-schuermann** [comment]
I'll change to var. That's a better convention
