### ISSUE TITLE
switch statement style

### ISSUE THREAD

**Issue by j-hui** [shux-lang/shux#11]
This bugs me to no fucking end guys
> it grinds my gears
> it grinds my goats too
> it picks my bones
> it irritates my eyeholes
> it aggravates my arms
> it agitates my alveoli
> it upsets my MOSFETs
> it irks my bungalows

We should stick to one style for switch statements. Either:
```
foo:
  ay
| lmao
```
or
```
foo:
| ay
| lmao
```
or
```
foo:
  | ay
  | lmao
```
or
```
foo: ay
| lmao
```

*ples*

**Comment by Contentmaudlin** [comment]
I'm fine with:

```
foo:
| ay
| lmao```

**Comment by lucas-schuermann** [comment]
seconded
