### ISSUE TITLE
global and kn arg name conflict is okay

### ISSUE THREAD

**Issue by lucas-schuermann** [shux-lang/shux#111]
```
let int a = 5;

kn foo(int a) int {
   0
}

kn main() int {
   0
}
```

compiles, but it should fail since **a is redefined**. can someone take a look at this?

**Comment by Contentmaudlin** [comment]
@cerrno This is intended! CAST also does renaming so name conflict will not actually be a problem. 

Redefine is only not allowed within the same function scope e.g. formals + variable declarations cannot conflict. 

Moreover, lambdas can also introduce another layer of name overloading.
