### ISSUE TITLE
kn args can have the same name as globals

### ISSUE THREAD

**Issue by lucas-schuermann** [shux-lang/shux#115]
```
let int a = 5;

kn foo(int a) int {
   a
}

kn main() int {
   0
}
```

compiles without failure. unless this behavior is desired, this is a bug. shouldn't we easily just disallow name conflicts for better code practices anyways?

**Comment by Contentmaudlin** [comment]
Dude I just closed this issue lol

**Comment by Contentmaudlin** [comment]
https://github.com/shux-lang/shux/issues/111

See my comments

**Comment by lucas-schuermann** [comment]
LOL my bad

**Comment by lucas-schuermann** [comment]
wait dude this is wild--i literally wrote another test for this and used the exact same code, independent of the other one
