### ISSUE TITLE
ternary cond doesn't seem to be working

### ISSUE THREAD

**Issue by lucas-schuermann** [shux-lang/shux#119]
```
kn main() int {
   int a = 3;
   int b = 5;
   int z = (a == b) ? 5 : (a > b) ? 3 : 2;
   z
}
```

doesn't compile. can anyone see an error here that I am not missing? A nondescript parse error is thrown.

**Comment by lucas-schuermann** [comment]
this is only the case for this nested example. a single ? operator + expressions seems to work. see #120

**Comment by Contentmaudlin** [comment]
@cerrno I wrote this code and it seems to compile fine currently. Can you retest and confirm? Please close the issue if this is the case.

**Comment by lucas-schuermann** [comment]
As of the most recent test_suite push and pull from master, this still fails

```
kn main() int {
   int a = 3;
   int b = 5;
   int z = (a == b) ? 0 : 7;
   z
}
```

**Comment by lucas-schuermann** [comment]
```
Uncaught exception: Parsing.Parse_error Raised at file "parsing.ml", line 136, characters 14-25 Called from file "parsing.ml", line 162, characters 4-28 Re-raised at file "parsing.ml", line 181, characters 14-17 Called from file "shuxc.ml", line 28, characters 11-46
```

**Comment by lucas-schuermann** [comment]
work after pulling master into #120
