### ISSUE TITLE
Makefile doesn't do much

### ISSUE THREAD

**Issue by j-hui** [shux-lang/shux#13]
atm the `Makefile` only builds our scanner.

Someone needs to get familiar with the `corebuild` API and modify the `Makefile` to also do stuff like `ocamlyacc parser.mly` and compile + link all that stuff with the `ast.mli`

**Comment by j-hui** [comment]
@cerrno can we get this working asap? as soon as i finish on frontend, andy is gonna be blocked on this

**Comment by j-hui** [comment]
So while i was working on the AST->parser stuff, I added a couple of things to `make` it do something. Not really sure how or what it's doing though, but at least it's doing _something_ that's along the lines of trying to compile it.

**Comment by Contentmaudlin** [comment]
For now I have a fully working pipeline with the dependencies set. We might wanna switch to corebuild. See commit.

**Comment by lucas-schuermann** [comment]
We can switch to core build but I'm not sure what the large advantage would be. This project won't have many files, and most will just be additional objects to build with `ocamlc`

**Comment by Contentmaudlin** [comment]
A main advantage is that corebuild organizes the binaries you have. After making, your directory doesn't look like a mess.

**Comment by lucas-schuermann** [comment]
I'll take a look in the near future then. we can also considering moving to flat src directory in that case

**Comment by lucas-schuermann** [comment]
Closing for now. Will improve as required.
