### ISSUE TITLE
Change of policy for array declarations

### ISSUE THREAD

**Issue by Contentmaudlin** [shux-lang/shux#135]
Arrays cannot be declared without a size. Anything that will go over the size needs to truncate the number of elements return by the expression on the right.

- `int[5] x = /* expr */`  This will get the first 5 elements of expr into x
- `int[] x = /* expr */` this is simply illegal

**Comment by Contentmaudlin** [comment]
@cerrno Gonna need tests for these as well my man

**Comment by Contentmaudlin** [comment]
Exception is array formals, where they can be declared without a number between the brackets.

**Comment by lucas-schuermann** [comment]
I'll get tests done ASAP. likely after algos+ML because those are my heavy classes
