### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by Contentmaudlin** [shux-lang/shux#2]
Maybe make makefile better in the future

**Comment by lucas-schuermann** [comment]
Testing slack GitHub bot with a comment.

**Comment by j-hui** [comment]
Definitely – there seems to be two popular options to use in the toolchain. One of them is `ocamlbuild` but i forget what the other one is. 

We should consult kevin on this. @cerrno can you see what note hstag does?

**Comment by j-hui** [comment]
`corebuild` is what kevin suggested

**Comment by lucas-schuermann** [comment]
Pushing branch with changes solving this soon
