### ISSUE TITLE
Make does all by default

### ISSUE THREAD

**Issue by j-hui** [shux-lang/shux#40]
typing just `make` should only build our target.. right now it just makes `all` by default.

we should have this rule up at the top:
```
default: $(TARGETS)
```

Also `default` and `all` and `hello` are all `.PHONY` targets.

**Comment by andylhxu** [comment]
Acked. We will fix this later once we are done with hello world.

**Comment by lucas-schuermann** [comment]
What is the status with this? Are we still seeing the same weird compilation order problems?

**Comment by andylhxu** [comment]
#44 addressed

**Comment by andylhxu** [comment]
#48 fixed this issue, we can close it now.

**Comment by andylhxu** [comment]
Closing this issue now
