### ISSUE TITLE
non-trivial scalar literals are not handled properly

### ISSUE THREAD

**Issue by lucas-schuermann** [shux-lang/shux#82]
kn main() int {
   scalar x = 2.0;
   scalar y = 2.0e5;
   x = 2.0e-5;
   0
}

does not compile, throws parse error (without specific description string)

**Comment by Contentmaudlin** [comment]
We are yet to do this. See issue #4

**Comment by lucas-schuermann** [comment]
@j-hui  did we want to even try to support this or just say fuck it for now?
