### ISSUE TITLE
see test_suite branch: basic assignment type checking failing

### ISSUE THREAD

**Issue by lucas-schuermann** [shux-lang/shux#87]
for example,

kn main() int {
   int x = 1;
   x = "potato";
   0
}

compiles..?

**Comment by Contentmaudlin** [comment]
Two things:
- This shouldn't compile anyway because `x` is immutable. It needs a "var" for this assignment to be possible.
- I have tested this and it seems to throw the appropriate error.

**Comment by lucas-schuermann** [comment]
Fixed and now compiles
