### ISSUE TITLE
change test failure criteria to pattern match error strings rather than `exception`

### ISSUE THREAD

**Issue by lucas-schuermann** [shux-lang/shux#88]
see title--this would help to verify that useful error messages are being displayed

**Comment by Contentmaudlin** [comment]
I think we can sync this with the exceptions file John and I are building

**Comment by lucas-schuermann** [comment]
great. for reference, if you want to write/modify some yourself, a `.test` file is of the form

```
TYPE
keyword(s) keyword2 ...
```

where I'd just sub in part of the expected error string for the `keyword(s)` line

**Comment by lucas-schuermann** [comment]
also, for posterity, when you specify failure keywords, `TYPE` must be `FAIL`. The others are `COMPILE`, which tests if it compiles validly, and `PASS`, which tests running against a desired output
